const Categorie = [
  {
    id: "7",
    color: "B5C7DE",
    title: "Computers, Laptops",
    desc: "",
    img: "https://res.cloudinary.com/exon-media-com/image/fetch/c_scale,f_auto/https%3A%2F%2Fm.media-amazon.com%2Fimages%2FI%2F41H4HB6-LeL._SL160_.jpg",
    categorie: "Electronics",
    temas: [
      "Tablets",
      "Laptops",
      "Monitors",
      "Desktop Computers",
      "Routers",
    ],
  },
  {
    id: "13",
    color: "B5C7DE",
    title: "Smart Home Devices",
    desc: "",
    img: "https://res.cloudinary.com/exon-media-com/image/fetch/c_scale,f_auto/https%3A%2F%2Fm.media-amazon.com%2Fimages%2FI%2F51GAFkGk8gL._SL160_.jpg",
    categorie: "Home and Kitchen",
    temas: [
      "Robotic Vacuums",
      "Stick Vacuums",
      "Air Fryers",
      "Fryers",
      "Heating",
    ],
  },
  {
    id: "5",
    color: "B5C7DE",
    title: "Accessories",
    desc: "",
    img: "https://res.cloudinary.com/exon-media-com/image/fetch/c_scale,f_auto/https%3A%2F%2Fm.media-amazon.com%2Fimages%2FI%2F511jpQMlG2L._SL160_.jpg",
    categorie: "Baby",
    temas: [
      "Car Seats",
      "Video Monitors",
      "Breast Pumps",
      "Baby Monitors",
      "High Chairs",
    ],
  },
  {
    id: "8",
    color: "B5C7DE",
    title: "Consumer Electronics",
    desc: "",
    img: "https://res.cloudinary.com/exon-media-com/image/fetch/c_scale,f_auto/https%3A%2F%2Fm.media-amazon.com%2Fimages%2FI%2F51EEmkLLYoL._SL160_.jpg",
    categorie: "Tools and Home Improvement",
    temas: [
      "Screwdrivers",
      "Electric Heaters",
      "Thermostats",
      "Hammer Drill",
      "Laser Levels",
    ],
  },
  {
    id: "9",
    color: "B5C7DE",
    title: "Gaming and Console",
    desc: "",
    img: "https://res.cloudinary.com/exon-media-com/image/fetch/c_scale,f_auto/https%3A%2F%2Fm.media-amazon.com%2Fimages%2FI%2F41isrmDhtnS._SL160_.jpg",
    categorie: "Automotive",
    temas: [
      "Jump Starters",
      "Exterior Bulbs",
      "Car Battery Chargers",
      "Travel Coolers",
      "Engine Diagnostic Systems (OBD-II)",
    ],
  },
  {
    id: "4",
    color: "B5C7DE",
    title: "Smartphones",
    desc: "",
    img: "https://res.cloudinary.com/exon-media-com/image/fetch/c_scale,f_auto/https%3A%2F%2Fm.media-amazon.com%2Fimages%2FI%2F51IyU8endKL._SL160_.jpg",
    categorie: "Electronics",
    temas: [
      "Smartphones",
      "Tablets",
      "Phone Accessories",
      "Smartwatches",
      "Bluetooth Earbuds",
    ],
  },
];

export default Categorie;
export default Categorie;